apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gonf1i6jm-python-gitops
  description: This is GitOps manifest for gonf1i6jm-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gonf1i6jm-python
    backstage.io/kubernetes-id: gonf1i6jm-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gonf1i6jm-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gonf1i6jm-python
