apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gonf1i6jm-python
  janus-idp.io/tekton: gonf1i6jm-python
  backstage.io/kubernetes-id: gonf1i6jm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gonf1i6jm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
